import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'error': '#ba1a1a',
        'on-primary-container': '#f8f7ff',
        'surface-tint': '#0054d6',
        'surface-dim': '#dcd9dc',
        'surface-container-high': '#eae7ea',
        'tertiary-fixed-dim': '#c6c6cb',
        'error-container': '#ffdad6',
        'primary': '#0050cb',
        'on-secondary-fixed-variant': '#454749',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#424656',
        'on-tertiary-fixed': '#1a1c1f',
        'inverse-primary': '#b3c5ff',
        'tertiary': '#58595e',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#f3f0f2',
        'outline': '#727687',
        'on-secondary-container': '#616365',
        'on-secondary-fixed': '#1a1c1d',
        'on-error-container': '#93000a',
        'surface-container-low': '#f6f3f5',
        'on-tertiary-fixed-variant': '#45474b',
        'surface-container-lowest': '#ffffff',
        'surface': '#fcf8fb',
        'outline-variant': '#c2c6d8',
        'primary-container': '#0066ff',
        'on-primary': '#ffffff',
        'secondary-container': '#dfdfe1',
        'surface-container': '#f0edef',
        'on-error': '#ffffff',
        'on-tertiary-container': '#f8f8fd',
        'on-background': '#1b1b1d',
        'background': '#fcf8fb',
        'secondary-fixed': '#e2e2e4',
        'surface-container-highest': '#e4e2e4',
        'tertiary-container': '#717276',
        'primary-fixed': '#dae1ff',
        'on-primary-fixed': '#001849',
        'surface-bright': '#fcf8fb',
        'inverse-surface': '#303032',
        'primary-fixed-dim': '#b3c5ff',
        'on-primary-fixed-variant': '#003fa4',
        'surface-variant': '#e4e2e4',
        'on-surface': '#1b1b1d',
        'secondary-fixed-dim': '#c6c6c8',
        'tertiary-fixed': '#e2e2e7',
        'secondary': '#5d5e60',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-gap-md': '80px',
        'margin-desktop': '40px',
        'section-gap-lg': '160px',
        'container-max-width': '1200px',
        'gutter': '24px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'headline-lg': ['var(--font-montserrat)', 'sans-serif'],
        'label-bold': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'display-xl': ['var(--font-montserrat)', 'sans-serif'],
        'display-xl-mobile': ['var(--font-montserrat)', 'sans-serif'],
        'caption': ['var(--font-inter)', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-montserrat)', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'headline-md': ['var(--font-montserrat)', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['56px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['17px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'display-xl': ['80px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl-mobile': ['48px', { lineHeight: '1.1', letterSpacing: '-0.01em', fontWeight: '700' }],
        'caption': ['12px', { lineHeight: '1.4', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '0em', fontWeight: '600' }],
        'body-lg': ['21px', { lineHeight: '1.5', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', letterSpacing: '0em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}

export default config
